const SET_READY = "IS_READY";
const SET_LOADING = "SET_LOADING";
const SET_QUESTIONS = "SET_QUESTIONS";
const SET_ERROR = "SET_ERROR";
const SET_CORRECTION = "SET_CORRECTION";
const NEXT_QUESTION = "NEXT_QUESTION";
const OPEN_MODAL = "OPEN_MODAL";
const PLAY_AGAIN = "PLAY_AGAIN";

export {
  SET_READY,
  SET_LOADING,
  SET_QUESTIONS,
  SET_ERROR,
  SET_CORRECTION,
  NEXT_QUESTION,
  OPEN_MODAL,
  PLAY_AGAIN,
};
